name: OpenWrt Compile on /mnt (/dev/sda1)

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  openwrt-compile:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup /mnt using /dev/sda1 (simulate environment)
        run: |
          # NOTE: GitHub runners don't provide a real /dev/sda1,
          # but this simulates mounting and compiling in /mnt.
          # In a self-hosted runner, you could mount /dev/sda1.
          sudo mkdir -p /mnt
          sudo chown $USER:$USER /mnt

      - name: Show disk usage before build
        run: df -h /mnt

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y build-essential git

      - name: Clone OpenWrt source to /mnt
        run: |
          git clone --depth=1 https://github.com/openwrt/openwrt.git -b openwrt-24.10 /mnt/openwrt

      - name: Compile OpenWrt (config minimal, example)
        working-directory: /mnt/openwrt
        run: |
          # Install feeds
          ./scripts/feeds update -a
          ./scripts/feeds install -a

          # Default config, minimal
          make defconfig

          # Build toolchain only (as a test, full firmware takes too long)
          make toolchain -j$(nproc)

      - name: Show disk usage after build
        run: df -h /mnt

      - name: List build output
        run: ls -lh /mnt/openwrt/bin/targets || true
